### ISSUE TITLE
Further Evaluation of Query Results

### ISSUE THREAD

**Issue by bdsullivan** [spacegraphcats/spacegraphcats#104]
Dominik and I agree that we'd like to evaluate things equivalent to containment/similarity/overhead with respect to the k-mers themselves (not just the hashes). 

That is, if we think of our process as working like this: 

Q_k ->(minhash) -> Q ->(search CAtlas) ->  L ->(map back to cDBG) -> S ->(list k-mers) -> S_k

That is, Q_k and S_k are sets of k-mers, representing the query and the return of the search algorithm. 
L is the set of leaves in the CAtlas, S is the set of cDBG nodes that are associated with the leaves L, and Q is the minhash sketch that we use in our search algorithm. 

We'd like to be able to compare Q_k and S_k. This needs some infrastructure that we believe @ctb will have to help with, since we have no idea how Q is being generated right now (or how to backtrace S_k from S given the data files we have access to).

**Comment by bdsullivan** [comment]
Follow up: @ctb says first priority is to fix walk_dbg to do "the right thing" with respect to cDBG nodes which contain a single k-mer.

**Comment by ctb** [comment]
#105 fixes walk_dbg to do The Right Thing with single k-mer nodes.

One way to retrieve the full k-mer complement is to create an index on, or a leveldb containing, the contigs file. Since the sequence names in the contig are the cDBG node IDs, it will be straightforward to recover the sequences for S_k, decompose them into k-mers, and do whatever we want. For the query, of course, we have everything we need already.

Another way to do this is to create minhash signatures with lower compression ratios (of, say, 10, or 2, or 1). This is already implemented in the code base -- just changed --scaled to the desired number.  But the files involved will be very large and unwieldy for anything but acido and shew-reads...

In any case the answer will in theory be quite clear - the banding approach limits the divergence of the minhashes from the true Jaccard pretty strictly, although I don't have the math worked out.

**Comment by ctb** [comment]
The `extract_reads_by_frontier` script now allows this.

**Comment by ctb** [comment]
(Well, and `extract_contigs_by_frontier` gives the S_k. Happy to provide scripts to calculate whatever here, but I think we are discussing this elsewhere in detail now - c.f. https://github.com/TheoryInPractice/cats-in-practice/issues/17)
