### ISSUE TITLE
File naming conventions for catlases at multiple radii.

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#126]
Currently, we always write to `catlas.csv` and `first_doms.txt` regardless of the desired radius.  It seems wrong to overwrite those files if we want to do experiments at multiple radii.  We should change this to something like `3.catlas` or `5.domfile` to prevent collisions.

**Comment by bdsullivan** [comment]
This seems like a good idea to me. For anything already computed on our test datasets, you should go back and re-name existing files to match the new conventions to avoid expensive re-computation.

**Comment by ctb** [comment]
A few thoughts, from running into mild frustrations with this 6 months ago.

- it would be nice to have a selector mechanism that defaulted to the only radius there, and otherwise kicked back a "please pick one"; this would be nicer than requiring that we figure out which radius was calculated when at the end of the day there's only one.

- in #123 I'm preparing the way for a similar approach in the minhashes.db, where we can potentially have multiple combinations of scaled/ksize/track_abundance. Briefly, I write a file `minhashes_info.json` that contains (currently) only one entry --

```
[{"scaled": 1000.0, "ksize": 31, "track_abundance": false}]
```

  in the future I expect to expand this to contain multiple entries with a leveldb filename that 
  corresponds to each entry.  I could also add something that corresponds to a specific catlas.

- while one solution is indeed to do the above, I worry that with catlas radii, we will run into confusion and directories full of many files, when we could simply instead have different catlas directories for different radii and maybe modify the catlas code to take in a cDBG from a different catlas directory when computing the catlas (or just link those files in manually). 

  to rephrase this concern: what is wrong with having a different directory for each catlas radius setting? it seems less prone to confusion.

- in all of this it would also be nice to add some kind of provenance info to the catlas directory so we can see what commands were run. e.g. I would like to know what memory size was used with walk_dbg, on what input files and with what other parameters; same for each construction step.

  past experience suggests that a simple logfile to which we append would be sufficient, especially if we include the full sys.argv of each run along with (maybe) the git commit of spacegraphcats that we used.

  I think the logfile is probably more important and easier to do than any of this other stuff, TBH, because it will directly help us avoid confusion.

**Comment by bdsullivan** [comment]
Do we want to make creating a logfile a separate issue that can be addressed first (potentially before we resolve all these other questions)?

**Comment by ctb** [comment]
yes!

**Comment by ctb** [comment]
In #161 I implemented this properly for minhashes - see https://github.com/spacegraphcats/spacegraphcats/pull/161/files#diff-befee1eec8c9c44bc222a71e7f66c577R362. Works fine, not confusing so far. I could hack something together for catlas radiuses too, if people still think it's a good idea.
