### ISSUE TITLE
Inefficient computation

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#27]
We discovered today that some runs that appeared to be in an infinite loop actually are just running very slowly as a result of really inefficient methods and redundant computation.  Specific examples in [catlas.py](https://github.com/spacegraphcats/spacegraphcats/blob/master/spacegraphcats/catlas.py) and [search_for_domgraph_nodes.py](https://github.com/spacegraphcats/spacegraphcats/blob/master/search-for-domgraph-nodes.py):

1.  The `Catlas.shadow()` and `Catlas.leaves()` methods should do so with a DFS, but actually re-traverse paths already reached because they don't mark nodes as visited.
2.  The `Catlas.nodes()` method appears to only output the nodes passed to it in the argument `select`.
3.  When computing the spec/sens, we copy the leaves of the query into the `pos_nodes` variable, but don't subsequently alter it.

Assuming that we will support multiple search strategies, we need to come up with a common API across searches and ensure that we are not computing the same thing in multiple places.

**Comment by ctb** [comment]
> Assuming that we will support multiple search strategies, we need to come up with a common API across searches and ensure that we are not computing the same thing in multiple places.

I have no strong opinion on whether or not we should support multiple
search strategies.

**Comment by ctb** [comment]
On Fri, Nov 18, 2016 at 11:14:54AM -0800, sgsmob wrote:
> We discovered today that some runs that appeared to be in an infinite loop actually are just running very slowly as a result of really inefficient methods and redundant computation.

One more thought --

the main block to generating information for a paper is currently the fact
that on real-size data sets the frontier search doesn't complete in a
reasonable time. So ... more focused/less general optimization is fine
in the short term.

**Comment by sgsmob** [comment]
2 questions and a comment:

1.  Is mircea a real-sized data set?
2.  What constitutes a "reasonable amount of time"?
3.  The fixes we have are really big issues so they definitely should be addressed in the short term.

**Comment by ctb** [comment]
1. Mircea is at the lower end of a real-sized data set, i.e. most real data sets will probably be bigger, but if we can get it to work in a reasonable amount of time then the rest can be accomplished with optimization or bigger computers. It *is* the largest data set for which we actually known the answer (because it was constructed), I believe, so it will be a piece de resistance of our evaluation strategy.

2. "Reasonable amount of time"... if the search itself takes more than a minute with unoptimized Python code (i.e. no C++/Cython stuff), that's probably too long for practical use.

**Comment by ctb** [comment]
Relevant: https://github.com/spacegraphcats/spacegraphcats/issues/26#issuecomment-261727861
