### ISSUE TITLE
Output forward and reverse reads as interleave pairs with extract_reads

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#284]
Right now, `extract_reads` returns only the forward (or reverse) read in a pair of reads if only the forward (or reverse) read contains a kmer in the query nbhd. Is it possible to return both the forward and reverse read as interleaved pairs? I'm not sure this is desirable behavior, but it strikes me as being so for all biological purposes of nbhd queries. This would enable better use of sgc output by downstream tools (e.g. megahit, singlem, anything that performs better with paired-end reads) 

See https://github.com/wwood/singlem/issues/52 for an example of how to get around not having paired-end reads.

**Comment by ctb** [comment]
hmm. I'll have to think more about this. Right now I can't think of a way to do this that doesn't involve rebuilding the database... but it should be possible somehow.

**Comment by ctb** [comment]
So, the problem is that `spacegraphcats.search.extract_reads` uses the `reads.bgz.labels` index to go from unitig to read offset in the BGZF file. We would need to regenerate this labels file (which is pretty time consuming) so that it contained the _first_ read whenever there's a pair.

As it is, we could easily output the second read whenever there's a pair and we are already outputting the first read.

One alternative is to seek backwards in the BGZF file, which sounds complicated and error prone...

**Comment by taylorreiter** [comment]
This isn't information I need immediately, but I think it would be helpful for future applications. Is it possible to regenerate hte labels to contain the first read whenever there is a pair in v2.0 or something?

**Comment by ctb** [comment]
On Tue, Jul 28, 2020 at 11:13:50AM -0700, Taylor Reiter wrote:
> This isn't information I need immediately, but I think it would be helpful for future applications. Is it possible to regenerate hte labels to contain the first read whenever there is a pair in v2.0 or something?

yes, should be no problem.

**Comment by ctb** [comment]
question for @taylorreiter - do you exclusively use /1 and /2 to indicate paired reads, or do we need to support something other formats?

**Comment by taylorreiter** [comment]
I have exclusively used /1 and /2...I feel like supporting whatever is on the SRA should be sufficient but I'm not well versed in different labeling types for forward/reverse reads.
