### ISSUE TITLE
Component-wise computation

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#39]
One source of slowdown might be from collisions in the large set sizes.  As far as I know, all the computation for building the Catlas can be done independently in each component of the graph.  In order to keep set size and memory usage down, we should do the computation one component at a time and then combine them at the end.

Some design decisions to consider:

* Should we precompute the components and save them in separate files?
* Should the functions take a list of components as arguments or should we loop through components and call the functions on them individually?
* What does the Catlas for the entire graph look like?  The top catlas level could be a node that points to the root of each component, but other options might be possible.

**Comment by ctb** [comment]
On real data sets, there is only one component, generally.  This is for
several reasons, both real (shared k-mers between even quite distant
critters) and "false" (sequencing errors).

Sorry :(

**Comment by sgsmob** [comment]
Why does the Hu data set have > 300k components?

**Comment by ctb** [comment]
That's unexpected :). Are you sure?!

Generally we have found that everything collapses into a single very large
component.  You can get minor components due to errors in sequencing, but back
when we were examining this for large data sets we never found a real data set
with multiple significantly sized components...

(We worked on this for about 3 years as part of the Pell et al. 2012 PNAS paper, which proposed this as a solution for metagenome assembly scaling.)

**Comment by sgsmob** [comment]
According to the printout in `build-catlas.py`:

> Loaded graph with 54583987 vertices, 64166942 edges and 302412 components
