### ISSUE TITLE
thoughts about annotating a cDBG with protein queries

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#437]
If #379 can be finagled to operate like `multifasta query`, then protein queries could be used to annotate a cDBG. 
One thing I've run into trouble with in annotating cDBGs with nucleotide `multifasta queries` is that the multifasta file I query with isn't complete, e.g. many of the nodes in the cDBG/level 1 dominating set don't end up being annotated because their is no way to generate sufficient reference sequences (I'm guessing this is because of HGT, etc). #428 has numbers for # nodes annotated with different multifasta queries. It was a pain generating each of the multifasta queries -- because I knew the taxonomic identity of my catlas, I downloaded all the isolates genomes from refseq for those genomes. I also made my own gene catalogs by assembling and predicting genes from each query nbhd from the metagenomes. Which is to say, it was A LOT of work and a lot of compute and some really annoying snakemake rules. There is a lot of room for user-experience improvement for annotating a cDBG/catlas.

Using protein queries may annotate more of the graph, and be easier. 

To understand whether this has a chance of being accurate, I think we could check and see how many k-mers are shared between orthologs. If most kmers are unique to ortholog families, we could generate a set of kmers that are unique to each ortholog family and annotate the graph using these. While it would be wonderful to predict orthologs from all the genes in all the genomes in GTDB, that's probably too heavy handed for a test idea. May be quick and easy to download AA seqs that lead to pfam profiles, make a protein signature for each profile, and compare them. If there's low overlap, this could be a tractable idea. 

@bluegenes has done some of this work, more later!

**Comment by ctb** [comment]
I see no reason why this couldn't all work quite easily (protein annotation specifically, and improvement of UX overall). Let's talk about it in person and then drop some notes here so I have a more specific direction to go in!

**Comment by ctb** [comment]
OK, digging around now ;).

It sounds like what you want is the file `multifasta.cdbg_annot.csv` (produced by rule `build_cdbg_list_by_record` in the spacegraphcats Snakefile), but produced using protein sequences instead of DNA sequences.

Tracing this back in the process, the key file seems to be `multifasta.pickle`, produced by rule `build_multifasta_index` using the script `spacegraphcats.search.index_cdbg_by_multifasta`.  This takes in the `multifasta_reference` from the config.

So, you would like to have the `multifasta_reference` from the config be something that can be either DNA or protein, and it would then work accordingly. I think it should also be straightforward to have the input be DNA or protein, with the appropriate matrix of options:
- DNA vs DNA search in unitigs (think blastn; this is the current behavior)
- translated DNA vs translated unitigs (tblastx)
- protein query vs translated unitigs (tblastn)

This should be straightforward to do 🎉 .

Main question: would you prefer (1) the translated version of this be a separate, parallel set of rules in the workflow (so, new filenames on both query and output side), or would you like it to be (2) integrated into the current Snakefile as a new config option (`multifasta_reference_type` and `multifasta_search_type` or something) that produces the same filenames?

**Comment by taylorreiter** [comment]
hmm I don't think I have strong opinions, so I think whichever would be easiest to encode/maintain i'm fine with. 
I guess my one opinion is that it would be nice if the output file names would allow for results from both DNA or protein queries without having files overwrite one another.

**Comment by ctb** [comment]
simple enough - thanks!

**Comment by ctb** [comment]
working on this over in https://github.com/spacegraphcats/spacegraphcats/pull/444

**Comment by taylorreiter** [comment]
#444 & #379 have been great! As noted in the PR, I love the output files from #444 and in the long run they're a great format that supports all the things I need them to have (and, you know, hopefully other people will like them too).

I've been using #379 to assess the accuracy of #444 (or really, just protein searches in general, which need to be accurate for #444 to be useful). I used #379 to extract reads from nbhds that overlap with a single protein query, and then looked at FP/FN/TP/TN rates. From the results, which I wrote up in #379, I think the best approach moving forward would be to use a gather-like approach for multifasta query, where `threshold_kmers` (default 1) is enough to annotate a cDBG nodes as the query, but that only the best match is annotated until no matches are left. I know @ctb sort of suggested this in one of previous conversations, is this possible, and at the scale of ~all of PFAM (or eggnog or kegg or whatever database)? PFAM has ~20k protein families and I think a total of 4 million fasta sequences. Also, what database structure would be necessary to have this work?

**Comment by ctb** [comment]
Closing this now in favor of #448 :)
